#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Welcome to Gadget County
#+date: <2022-05-26 Thu>
#+author: Clifford Wulfman
#+email: cwulfman@PU-C02C37EKMD6T
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.1 (Org mode 9.5.2)
#+cite_export:

Welcome to Gadget County!

Gadget County is located in the northern portion of the state of
Farallon.  There are four precincts in the County: the Downtown
Precinct is the part of the county that’s in Orbit City but not in the
SpacePort District; the Spacetown Precinct is the part of the county
that’s both in Orbit City and the SpacePort District; the Port
Precinct is the part of the county that’s in the SpacePort District
but not in Orbit City; the Bedrock Precinct is the part of the county
that’s in neither Orbit City nor the SpacePort District (named for a
predecessor town that archaeologists found traces of in the remote
part of the county).

All residents of Gadget County can vote in national and state
elections.  They may also vote in elections for any seat on
the Gadget County Board of Supervisors, and also on any county-level
ballot question. That’s all that Residents of the Bedrock Precinct can
vote for.  In addition to county voting, residents of the Downtown
and Spacetown Precincts can vote for Orbit City Council and Orbit City
Mayor, and any city-level ballot question.  In addition to county
voting, residents of the Spacetown Precinct and Port Precinct can for
vote for the Spaceport Control Board.

The Gadget County Elections Board runs elections for the electoral
district that is the county itself (including national, statewide, and
state level elections), as well as the two jurisdictions within the
county: Orbit City with its offices for City Council and for Mayor;
and the Spaceport District, with its offices for the Spaceport Control
Board that regulates the use of the SpacePort and who supervise staff
activity to collect landing fees and use funds for spaceport upkeep.

