#+title: An Introduction to CVR
#+date: <2021-11-12 Fri>
#+author: Clifford E. Wulfman
#+email: cliff@osetfoundation.org

A cast vote record (CVR) is an electronic record of a voter's
selections produced by a vote-capture device such as a ballot scanner.
Election results are produced by tabulating a collection of CVRs, and
audits can be performed by comparing voters' paper ballots with the
CVRs.

The Cast Vote Records CDF Specification (NIST SP 1500-103) is a
format specification for CVRs, developed by NIST to provide an
interoperable, non-proprietary data-exchange format for cast vote
records, in order to facilitate the exchange of CVRs among devices
regardless of manufacturer.  The specification is defined in
[[https://doi.org/10.6028/NIST.SP.1500-103]], as well as in a [[https://github.com/usnistgov/CastVoteRecords][public
GitHub repository]], which also includes a UML specification and XML and
JSON schemas defining the standard, as well as several example
records.

We have included here a number of additional sample records, as well
as an annotated overview.
